# Generated by Django 5.0.3 on 2024-03-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_v1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_name",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="user name"
            ),
        ),
    ]
