# Generated by Django 5.0.3 on 2024-03-19 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_v1", "0003_districts"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Districts",
        ),
    ]
