# Generated by Django 5.0.3 on 2024-03-19 05:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_v1", "0005_customuser_role_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="region name"
            ),
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(unique=True)),
                ("calendar", models.DateTimeField(default=django.utils.timezone.now)),
                ("article_сriminal_сode", models.IntegerField()),
                (
                    "performance",
                    models.CharField(
                        choices=[
                            ("вложение", "attachment"),
                            ("обнаружение трупа", "discovery corpse"),
                            ("ск.смерть", "sk.death"),
                            ("БВП Совершеннолетний", "BVP adult"),
                            ("утеря вещей", "Loss items"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "date_referral",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "where_order_sent",
                    models.CharField(
                        choices=[
                            ("ОМПС", "OMPS"),
                            ("служба пробации", "probation service"),
                            ("местные испол.органы", "local executive bodies"),
                            ("учреждения образования", "educational institutions"),
                            ("медицинские учреждения", "medical institutions"),
                            (
                                "субъекты частного бизнеса (ИП, ЧП)",
                                "private business entities",
                            ),
                            (
                                "производительные предприятия (заводы, фабрики и др)",
                                "productive enterprises",
                            ),
                            (
                                "иные учреждения, организации и объединения",
                                "other institutions, organizations and associations",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("review_period", models.IntegerField(default=30)),
                ("response_received", models.DateTimeField(blank=True, null=True)),
                ("submissions_reviewed_deadline", models.BooleanField(default=False)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="api_v1.region",
                    ),
                ),
            ],
        ),
    ]
